version: "3.8"
services:
  db:
    image: postgres:14.2
    env_file: .env
    ports:
      - "6543:5432"
    volumes:
      - postgres_d:/var/lib/postgresql/data
    networks:
      - crossmint

volumes:
  postgres_d:

networks:
  crossmint:
    driver: "bridge"
